name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm ci
    - name: List installed packages
      run: npm list --depth=0
    - name: Lint
      run: npm run lint
    - name: Build
      run: npm run build
    # Remove or comment out the test step if you don't have tests yet
    # - name: Test
    #   run: npm test
